### ISSUE TITLE
Adapting to a different dataset

### ISSUE THREAD

**Issue by atoffano** [tigerchen52/Biomedical-Entity-Linking#4]
Hi, 
Thank you for sharing this work.

I am currently trying to adapt this model to a different dataset.
I've been able to successfully generate a KB, preprocess data and generate candidates.
However I am facing an issue when it comes to fitting the model.
Once the fit_generator() function is called, it simply returns a StopIteration error.
I suspect this is due to a slightly different dataset size. 

Do you have any idea whether that's a correct assumption ? And in either case how i can try to fix this issue ?

Thanks,
Antoine

**Comment by tigerchen52** [comment]
Hi Antoine,

Thanks for your interest in this work.

As for your technical issue, from my experience, the fit_generator needs to read data continuously, which means once the data size is limited, it will raise the StopIteration error. Perhaps try to use a loop to generate data samples repeatedly.

Hope this reply is helpful!

Best,
Lihu

**Comment by atoffano** [comment]
Thank you for your answer, it was helpful in understanding where the problem came from.

I managed to fix it and get things working properly.
The error was due to the addition of the context feature, which whenever a mention had an empty context (usually whenever the mention spans a whole sentence) crashed the code.

I've also been wondering about the steps_per_epoch parameter, which is by default 500.
The provided ncbi train dataset having 5932 datapoints, this means (from my understanding) that with a batch size of 64 each training mention is encountered at least 5 times per epoch.

Since i'm trying to adapt your method to another dataset, should i adapt the steps_per_epoch parameter to my dataset size so this ratio is still valid or would it be better to have a more standard approach so that each data point is only encountered once ?

Thank you in advance.
Antoine

**Comment by tigerchen52** [comment]
> Thank you for your answer, it was helpful in understanding where the problem came from.
> 
> I managed to fix it and get things working properly. T error was due to the addition of the context feature, which whenever a mention had an empty context (usually whenever the mention spans a whole sentence) crashed the code.
> 
> I've also been wondering about the steps_per_epoch parameter, which is by default 500. The provided ncbi train dataset having 5932 datapoints, this means (from my understanding) that with a batch size of 64 each training mention is encountered at least 5 times per epoch.
> 
> Since i'm trying to adapt your method to another dataset, should i adapt the steps_per_epoch parameter to my dataset size so this ratio is still valid or would it be better to have a more standard approach so that each data point is only encountered once ?
> 
> Thank you in advance. Antoine

Hi Antoine,

Your understanding is correct in terms of the number of training epochs.  Usually, the hyper-parameter should be slightly modified considering different datasets. For this purpose, you can use the cross-validation or the hold-out method to search the hyper-parameter. 
As for your second question, one epoch is usually not enough and there is a negative sampling during the training phase (see training section in our paper), which means negative samples are different in each epoch.

Best,
Lihu
